name: result_master
description: Offline School Result Management App with Excel XLSX parser, PDF engine, and SQLite.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Standard UI Icons
  cupertino_icons: ^1.0.8

  # Database storage
  sqflite: ^2.3.2
  path: ^1.9.0

  # Standard highly-compatible Excel package for Dart 3.3.0
  excel: ^4.0.6
  pdf: ^3.11.1

  # Native File Sharing sheet integration
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
