name: result_master
description: Offline School Result Management App with Excel-like marks workbook and SQLite autosave.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Standard UI Icons (Fixed version!)
  cupertino_icons: ^1.0.8

  # Database & File storage (Required for your SQLite app)
  sqflite: ^2.3.2
  path: ^1.9.0

  # Tools for our Error Logger & Log Exporting
  path_provider: ^2.1.2
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
